### ISSUE TITLE
Find repo index.json example

### ISSUE THREAD

**Issue by pat2381** [kellerkompanie/kellerkompanie-sync-wpf#25]
Hi there,
you created a great tool for arma here. I would like to adapt this to my needs. But unfortunately I have no idea what the repo index.json looks like or how you created it. You still have an index.json file as an example? You no longer use the tool? Would be great if you can help me!

best regards
pat

**Comment by Schwaggot** [comment]
Sorry, didn't get a notification about this... the server side files are generated by this: https://github.com/kellerkompanie/kellerkompanie-sync-rust
However, be aware that the project was never actually finished due to limited manpower.
